FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dashboards/ ./dashboards/
COPY postgres/   ./postgres/
COPY configs/    ./configs/
COPY .env        ./.env

EXPOSE 8501

CMD ["streamlit", "run", "dashboards/app.py", \
     "--server.port=8501", \
     "--server.address=0.0.0.0", \
     "--server.headless=true"]
